// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArE7zlsFFoYL52-Qn8Ss2vnjNw2O63ORQ',
    appId: '1:825777531738:web:ae14300bdea1840306a163',
    messagingSenderId: '825777531738',
    projectId: 'immichtvapp',
    authDomain: 'immichtvapp.firebaseapp.com',
    storageBucket: 'immichtvapp.firebasestorage.app',
    measurementId: 'G-75ZH7P699V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArhnYjbuFyP87Np0n0pWSD_RKko4MDcfs',
    appId: '1:825777531738:android:5e1b5577c6f331ba06a163',
    messagingSenderId: '825777531738',
    projectId: 'immichtvapp',
    storageBucket: 'immichtvapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB90WWJm2JnTWicWZS7W5v19Lx0AHlMYRY',
    appId: '1:825777531738:ios:752206955c41565206a163',
    messagingSenderId: '825777531738',
    projectId: 'immichtvapp',
    storageBucket: 'immichtvapp.firebasestorage.app',
    iosBundleId: 'com.workwithafridi.immichtv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB90WWJm2JnTWicWZS7W5v19Lx0AHlMYRY',
    appId: '1:825777531738:ios:752206955c41565206a163',
    messagingSenderId: '825777531738',
    projectId: 'immichtvapp',
    storageBucket: 'immichtvapp.firebasestorage.app',
    iosBundleId: 'com.workwithafridi.immichtv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArE7zlsFFoYL52-Qn8Ss2vnjNw2O63ORQ',
    appId: '1:825777531738:web:fb4ff29689e7574706a163',
    messagingSenderId: '825777531738',
    projectId: 'immichtvapp',
    authDomain: 'immichtvapp.firebaseapp.com',
    storageBucket: 'immichtvapp.firebasestorage.app',
    measurementId: 'G-HSHMBZ4HYR',
  );
}
